# Generated by Django 6.0.1 on 2026-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://png.pngtree.com/element_our/png/20180930/food-icon-design-vector-png_120564.jpg', max_length=500),
        ),
    ]
