# Generated by Django 6.0.1 on 2026-02-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangowithfastapipydantic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Movies',
        ),
    ]
