# Generated by Django 6.0.1 on 2026-02-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangowithfastapipydantic', '0002_rename_item_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='typ',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
