# Generated by Django 6.0.1 on 2026-02-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangowithfastapipydantic', '0003_movies_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='images/None/None.jpg', upload_to='images/'),
        ),
    ]
